# Generated by Django 4.1 on 2023-05-26 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('zip', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state_name', models.CharField(max_length=100, verbose_name='State')),
                ('lat', models.FloatField(verbose_name='LATITUDE')),
                ('lng', models.FloatField(verbose_name='LONGITUDE')),
                ('id', models.IntegerField()),
            ],
            options={
                'db_table': 'app_delivery_location',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Template text')),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Weight')),
                ('location_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_to_locations', to='delivery.location', verbose_name='Location delivery')),
                ('location_pick_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_from_locations', to='delivery.location', verbose_name='Location pick-up')),
            ],
            options={
                'db_table': 'app_delivery_cargo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Address')),
                ('carrying_capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Carrying capacity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='delivery.location', verbose_name='Location')),
            ],
            options={
                'db_table': 'app_delivery_car',
                'ordering': ['id'],
            },
        ),
    ]
